version: '3.1'


# https://hub.docker.com/_/mariadb
# Use root/example as user/password credentials


services:
  db:
    build: ./mariadb
    image: mariadb
    restart: always

    volumes:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080